### ISSUE TITLE
It doesn't work on most distros.

### ISSUE THREAD

**Issue by butter-fly04** [ivan-hc/ocenaudio-appimage#1]
I tried running it on many Ubuntu based distros and Fedora, but it won't open on any distro other than Manjaro.

**Comment by ivan-hc** [comment]
in what sense "it won't open"?

Is `libfuse2` installed (on Fedora `yum install fuse fuse-devel`, on Debian-based distros `apt install libfuse2`)?

Have you made it executable (`chmod a+x ./*AppImage`)?

**Comment by butter-fly04** [comment]
LibFuse2 was installed on every distro, and the other Appimages were working, but not this one.

**Comment by ivan-hc** [comment]
Uhm... it runs well for me on Debian. Can you run the AppImage with LD_DEBUG to let me see the log? 

```
LD_DEBUG=libs ./*.AppImage
```
to see missing libraries.

If it is so, try to made a test by extracting the Appimage

    ./*AppImage --appimage-extract
    cd squashfs-root
and replace this line of the AppRun

    export LD_LIBRARY_PATH="${HERE}"/lib/:"${LD_LIBRARY_PATH}"
with this

    export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:"${HERE}"/lib/:"${LD_LIBRARY_PATH}"
and then run the AppRun

    ./AppRun

**Comment by butter-fly04** [comment]
Running the first command I got this error-

/tmp/.mount_ocenau3h0HEo/bin/ocenaudio: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

**Comment by ivan-hc** [comment]
This AppImage is only built usind the deb package, not other files are included.

What if you install `libbz2`?

Ubuntu: `apt install libbz2-dev`

Fedora (should be `bzip2-libs`): `yum install bzip2-libs` ? 

If this is not enough, extract the AppImage and replace the line I said before, and run the AppRun

**Comment by butter-fly04** [comment]
It says that-  Package bzip2-libs-1.0.8-13.fc38.x86_64 is already installed.
I extracted the file, but didn't understand what to do next.
There is no such line : cd squastfs-root

But I found in a forum that "libbz2.so.1.0" is "libbz2.so.1" in Fedora.
![Screenshot_20230723_114715](https://github.com/ivan-hc/ocenaudio-appimage/assets/126476160/3f263b01-ea99-4493-adcd-7441f5e45dc1)

**Comment by ivan-hc** [comment]
I was wrong, is `squashfs-root` (typing error).

However, I started a new Action and edited the AppRun to see system libraries https://github.com/ivan-hc/ocenaudio-appimage/commit/32188b2f0816ec856083011dc225eee000010b07

Its ready, download it now https://github.com/ivan-hc/ocenaudio-appimage/releases/tag/continuous and let me know if it works.

**Comment by butter-fly04** [comment]
No, shows same error as before.

**Comment by ivan-hc** [comment]
This time I've bundled it by including all the libraries from Ubuntu 20.04 "focal"

https://github.com/ivan-hc/ocenaudio-appimage/releases/tag/continuous

now it should work.

**Comment by butter-fly04** [comment]
got this-

/tmp/.mount_OcenauXX67tT/usr/bin/ocenaudio: error while loading shared libraries: libnsl.so.1: cannot open shared object file: No such file or directory

**Comment by ivan-hc** [comment]
I've seen that it is a library that cannot be bundled this way (is part of libc6), so I've modified LD_LIBRARY_PATH to made the AppImage see it.

Download it now https://github.com/ivan-hc/ocenaudio-appimage/releases/tag/continuous

**Comment by ivan-hc** [comment]
I restored previus builder and used the LD_PRELOAD trick

https://github.com/ivan-hc/ocenaudio-appimage/blob/26ed803f73892dc4ac31a5937d32487a72a2c0bd/ocenaudio.sh#L21

If you can see, I addes a line `export LD_PRELOAD=/usr/lib/libbz2.so.1:/lib/x86_64-linux-gnu/libbz2.so.1.0` to redirect to the system's library (one path is for Fedora, Arch and similar... the other is for Debian-based systems, you may take a message "cannot be preloaded" refering to one of the two paths, in case you have success I can silence the error with 2> /dev/null).

However about...

> I extracted the file, but didn't understand what to do next.

I can repeat a brief tutorial for you:

1. Extract the AppImage:
```
./*AppImage --appimage-extract
```
2. Once extracted, it will be generated a directory named "squashfs-root", use the `cd` command to enter it... or open a terminal into it manually, the important thing is you must run the script named "AppRun" into it.

The Apprun is onli a bash script, you can read and edit everything using your favourite text editor (nano, vim, mousepad, gedit... whatever you want).

All you have to do is to read the output message from the terminal when you exec `./AppRun`, for example:
```
/usr/lib/libcapocchia.so No such file or directory
```
and find where is this `libcapocchia.so` on your system... now it can be libcapocchia, libfangulo, libcazznesacc... the important thing is that you can insert that path in LD_PRELOAD. Check where is that path and change the line into the AppRun, from.. 

    export LD_PRELOAD=/usr/lib/libbz2.so.1:/lib/x86_64-linux-gnu/libbz2.so.1.0
...to...

    export LD_PRELOAD=/usr/lib/libbz2.so.1:/lib/x86_64-linux-gnu/libbz2.so.1.0:/lib/libpercoca.so
if libpercoca is in /lib. 

These are simple examples of bash scripting and terminal usage.

Once you have understand this, you can help me speed up closing this issue as soon as possible, because Ocenaudio as Appimage works for me on Debian, and I don't know what the hell happens on Fedora and Ubuntu, I only know they force the use of Flatpak and Snap on their systems, and this is not good.

**Comment by asadul04** [comment]
I have edited the file, now how can I execute the program with this edited file?

**Comment by butter-fly04** [comment]
I got these errors running the AppRun file

ERROR: ld.so: object '/usr/lib/libbz2.so.1' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/x86_64-linux-gnu/libbz2.so.1.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/home/asad/Downloads/squashfs-root/bin/ocenaudio: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

Also I found the file "libbz2.so.1.0.8" in the directory "/user/lib64/".

So the line would be: 
export LD_PRELOAD=/usr/lib/libbz2.so.1:/lib/x86_64-linux-gnu/libbz2.so.1.0:/lib64/libbz2.so.1.0.8

Isn't it like that?

**Comment by ivan-hc** [comment]
Yes, try to add /user/lib64/libbz2.so.1.0.8
...
/user? isn't it /usr?

**Comment by ivan-hc** [comment]
This line should be enough for all systems
```
export LD_PRELOAD=$(cd / && find . -name "libbz2*" 2>/dev/null | head -1 | cut -c 2-)
```

EDIT: first of all test the command `cd / && find . -name "libbz2*" 2>/dev/null | head -1 | cut -c 2-` and see if the output points to something like /user/lib64/libbz2.so.1.0.8 or something like this, the importat thing is that it is a library.

In case you receive other outputs about missing libraries, for example "libmissing.so.1.0", change the line above to...
```
export LD_PRELOAD=$(cd / && find . -name "libbz2*" 2>/dev/null | head -1 | cut -c 2-):$(cd / && find . -name "libmissing*" 2>/dev/null | head -1 | cut -c 2-)
```
and so on.

Finally, let me know if this works for you, so I'll add this in the next release.

**Comment by butter-fly04** [comment]
How can I execute this with edited AppRun file?

**Comment by ivan-hc** [comment]
```
./AppRun
```

**Comment by butter-fly04** [comment]
Tried two lines and it shows this same error.


![Screenshot_20230727_115555](https://github.com/ivan-hc/ocenaudio-appimage/assets/126476160/d9811366-7e7b-4b4a-a663-3c9afc8b717f)

**Comment by ivan-hc** [comment]
let me see the AppRun

**Comment by butter-fly04** [comment]
![Screenshot_20230727_121137](https://github.com/ivan-hc/ocenaudio-appimage/assets/126476160/4c9b266b-85d7-4dc9-a2d9-adc2ab83e5f0)

**Comment by ivan-hc** [comment]
Are you sure that libbz2 is installed?

**Comment by butter-fly04** [comment]
![Screenshot_20230727_121627](https://github.com/ivan-hc/ocenaudio-appimage/assets/126476160/5f1b2da3-0997-4aac-b0c7-618d05a9e4b6)

**Comment by ivan-hc** [comment]
got it, add /usr/lib64/ in LD_LIBRARY_PATH

**Comment by butter-fly04** [comment]
So the line would be:

export LD_PRELOAD=/usr/lib64/ in LD_LIBRARY_PATH

**Comment by ivan-hc** [comment]
no
```
export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:/usr/lib64/:"${HERE}"/lib/:"${LD_LIBRARY_PATH}"
```

**Comment by butter-fly04** [comment]
Like this?
![Screenshot_20230727_122207](https://github.com/ivan-hc/ocenaudio-appimage/assets/126476160/31a45fcb-b4fc-4b3e-9cbb-6d92f97f3ddc)

**Comment by ivan-hc** [comment]
```
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD=$(cd / && find . -name "libbz2*" 2>/dev/null | head -1 | cut -c 2-)
export QT_FONT_DPI=96
export QT_QPA_PLATFORMTHEME=$QT_QPA_PLATFORMTHEME
export PATH="${HERE}"/bin/:"${PATH}"
export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib64/:"${HERE}"/lib/:"${LD_LIBRARY_PATH}"
case "$1" in
	'') exec ${HERE}/bin/ocenaudio;;
	*) exec ${HERE}/bin/ocenvst "$*";;
esac
```

**Comment by butter-fly04** [comment]
now?

![Screenshot_20230727_122720](https://github.com/ivan-hc/ocenaudio-appimage/assets/126476160/1a3a1031-598e-4187-9e28-d9568dd8e57d)

**Comment by ivan-hc** [comment]
OK, run it

**Comment by butter-fly04** [comment]
![Screenshot_20230727_123108](https://github.com/ivan-hc/ocenaudio-appimage/assets/126476160/6ae9f0bf-59cf-4c97-9029-a1fdab68b0cc)

**Comment by ivan-hc** [comment]
Its really strange, the library is in place

**Comment by ivan-hc** [comment]
Replace the content of AppRun with this
```
#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export UNION_PRELOAD="${HERE}"
export LD_PRELOAD=$(cd / && find . -name "libbz2*" 2>/dev/null | head -1 | cut -c 2-):/usr/lib64/libbz2.so.1.0.8
export QT_FONT_DPI=96
export QT_QPA_PLATFORMTHEME=$QT_QPA_PLATFORMTHEME
export PATH="${HERE}"/bin/:"${PATH}"
export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib64/:"${HERE}"/lib/:"${LD_LIBRARY_PATH}"
case "$1" in
	'') exec ${HERE}/bin/ocenaudio;;
	*) exec ${HERE}/bin/ocenvst "$*";;
esac
```

**Comment by butter-fly04** [comment]
![Screenshot_20230727_124435](https://github.com/ivan-hc/ocenaudio-appimage/assets/126476160/31921095-c799-4287-858e-1e10cd3c8f37)
![Screenshot_20230727_124539](https://github.com/ivan-hc/ocenaudio-appimage/assets/126476160/73fa4f9f-385c-4cb1-b82d-f014be84ca7b)

**Comment by ivan-hc** [comment]
Just created an extra version based on JuNest that works really everywhere.

If you use it without one of my clients (AM and AppMan), download the one that contains the word "junest" in the name (the big one, about 100 MB) from...

https://github.com/ivan-hc/ocenaudio-appimage/releases/tag/continuous

If you are using [AM Application Manager](https://github.com/ivan-hc/AM-Application-Manager) or [AppMan](https://github.com/ivan-hc/AppMan), edit the AM-updater script into the directory where is installed ocenaudio (/opt/ocenaudio if you use AM, while if you use AppMan you are the one that knows where is installed) and change this line...

```
version=$(wget -q https://api.github.com/repos/$REPO/releases -O - | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i appimage | cut -d '"' -f 4 | head -1)
```
with this
```
version=$(wget -q https://api.github.com/repos/$REPO/releases -O - | grep -w -v i386 | grep -w -v i686 | grep -w -v aarch64 | grep -w -v arm64 | grep -w -v armv7l | grep browser_download_url | grep -i appimage | grep junest | cut -d '"' -f 4 | head -1)
```
and update with the option `-u`

This time I'm sure we have solved.

EDIT: in case you want to install the new version with the option `-i`, see `ocenaudio-junest`, it will also override the installed version

**Comment by ivan-hc** [comment]
Just replaced the version from AUR with the one from Chaotic-AUR:

https://github.com/ivan-hc/ocenaudio-appimage/commit/d45fee72a97762f1df2ce8e322e4b20cb6331605

the reasin is that the PKGBUILD is brocken, so I had issues when creating ocenaudio in JuNest. The version is older than the latest available, however it is a prebuilt package, so the daily update will not break the upload of the other release from .deb package.

In the moment I write, the version from Chaotic-AUR is 3.12.6, while the last one is 3.12.7.
